### ISSUE TITLE
utils_model & utils_image

### ISSUE THREAD

**Issue by Moaazallaham** [RaoUmer/SRResCGAN#4]
Thank you for sharing your great work.

I have been trying to train a model using my own data, but when running the main_sr_color.py, it results in the following error:

Traceback (most recent call last):
  File "main_sr_color.py", line 14, in <module>
    from utils import util
ImportError: cannot import name 'util' from 'utils' (C:\Users\moaaz\anaconda3\envs\zssr\lib\site-packages\utils\__init__.py)

At this point, I was unsure whether "utils" refer to the python package that is called "utils" or it is referring to the utils folder in the project main directory, so I disabled the "utils" package to narrow down the issue.  But that resulted in this error: 

Traceback (most recent call last):
  File "main_sr_color.py", line 15, in <module>
    from utils import utils_common
  File "E:\P10\SRResCGAN\training_codes\utils\utils_common.py", line 9, in <module>
    from utils import utils_image
ImportError: cannot import name 'utils_image' from 'utils' (unknown location)

Going back to the utils (the python package), i tried to find the utils_image & utils_model to see whether I have something wrong with my dependencies. But there I found out that python "utils" does not have those two (utils_image & utils_model )

So I am wondering whether I am missing those two files in the (training_codes\utils\) directory, or it is a problem with my dependencies.

Any help would be appreciated.

**Comment by RaoUmer** [comment]
Hi, I have added both files into `utils `directory. Sorry for this inconvenience. 
Thanks.

**Comment by Moaazallaham** [comment]
Thank you so much. I appreciate your help!
